spring.application.name=record_store
# Puerto de la aplicación
server.port=8080

# Configuración SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=record_store;encrypt=true;trustServerCertificate=true
spring.datasource.username=record_admin
spring.datasource.password=AdminRecord*
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect