spring.application.name=record_store
# Puerto de la aplicación
server.port=1433

# Configuración SQL Server
spring.datasource.url=${DB_URL}
#Eliminar/desactivar el usuario sa
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect