services:
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: recordStore-Sql

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "123recordStore"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./init-scripts:/init-scripts

    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr &
      sleep 25 &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '123recordStore' -C -i /init-scripts/01-schema.sql &&
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '123recordStore' -C -i /init-scripts/02-dml.sql &&
      wait
      "

volumes:
  sqlserver_data: